version: 2
jobs:
  unit-testing:
    working_directory: ~/rsm-select

    docker:
    - image: circleci/node:8.12

    steps:
    - checkout

    # download / cache dependencies
    - restore_cache:
      keys:
        - dependency-cache-{{ checksum "package.json" }}
        # fallback
        - dependency-cache-

    # install dependencies
    - run:
      name: Install Dependencies
      command: yarn install

    - save_cache:
      paths:
        - node_modules
      key: dependency-cache-{{ checksum "package.json" }}

    # run tests!
    - run:
      name: Run Unit Tests
      command: yarn test

workflows:
  version: 2
  workflow:
    jobs:
    - unit-testing
