version: 2
jobs:
  unit-tests:
    working_directory: ~/rsm-select
    docker:
    - image: circleci/node:8.12
    steps:
    - checkout
    - restore_cache:
        keys:
        - dependency-cache-{{ checksum "package.json" }}
        - dependency-cache-
    - run:
        name: Install Dependencies
        command: yarn install
    - save_cache:
        paths:
        - node_modules
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: Unit Tests
        command: yarn test
workflows:
  version: 2
  workflow:
    jobs:
    - unit-testing
